"""create chat history table

Revision ID: 74aa7ea3d061
Revises:
Create Date: 2025-05-15 00:30:34.598351

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74aa7ea3d061"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chathistory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_message", sa.String(), nullable=False),
        sa.Column("bot_response", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chathistory")
    # ### end Alembic commands ###
